issuer: https://accounts.google.com
# mgreau85-gh-pr-agt@mgreau85-chainguard.iam.gserviceaccount.com
subject: "109341865484100264303"

permissions:
  # to update PR titles and descriptions
  pull_requests: write
  contents: read
  checks: write

repositories:
  - driftlessaf-demo
