issuer: https://accounts.google.com
# mgreau85-gh-pr-val@mgreau85-chainguard.iam.gserviceaccount.com
subject: "112261605251656011849"

permissions:
  pull_requests: read
  contents: read
  checks: write

repositories:
  - driftlessaf-demo
  - melange
