issuer: https://accounts.google.com
# autofix@mgreau85-chainguard.iam.gserviceaccount.com
subject: "116574476489889966997"

permissions:
  # required to push commits with fixes to the fork
  contents: write
  # Allow to fix GitHub Actions workflow files
  workflows: write

repositories:
  - terraform-infra-common
  - enterprise-packages
  - mono
  
