issuer: https://accounts.google.com
# label-sla-cve-bot@mgreau85-chainguard.iam.gserviceaccount.com
subject: "104042916752870131337"

permissions:
  pull_requests: write
  contents: read
  checks: write

repositories:
  - stereo
