issuer: https://accounts.google.com
# autofix@mgreau85-chainguard.iam.gserviceaccount.com
subject: "104658657678730945684"

permissions:
  actions: read # Required to fetch workflow job logs
  checks: write
  contents: write
  pull_requests: write
  statuses: write
  workflows: write # Allow triggering actions when authoring commits.

repositories:
  - terraform-infra-common
  - enterprise-packages
  - mono
  
